{{- $v := include "cp-schema-registry.values" . | fromYaml -}}
{{- if $v.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "cp-schema-registry.fullname" . }}
  labels:
{{ include "cp-schema-registry.labels" . | indent 4 }}
spec:
  {{- if $v.podDisruptionBudget.minAvailable }}
  minAvailable: {{ $v.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if $v.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ $v.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
{{ include "cp-schema-registry.selectorLabels" . | indent 6 }}
{{- end }}
