{{- $v := include "cp-schema-registry.values" . | fromYaml -}}
{{- if $v.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cp-schema-registry.serviceAccountName" . }}
  labels:
{{ include "cp-schema-registry.labels" . | indent 4 }}
  {{- with $v.serviceAccount.labels }}
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- with $v.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
{{- end }}
