{{- if .Values.schema_registry.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cp-schema-registry.serviceAccountName" . }}
  labels:
{{ include "cp-schema-registry.labels" . | indent 4 }}
  {{- with .Values.schema_registry.serviceAccount.labels }}
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- with .Values.schema_registry.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
{{- end }}
