{{- $v := include "cp-schema-registry.values" . | fromYaml -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-schema-registry.fullname" . }}
  labels:
{{ include "cp-schema-registry.labels" . | indent 4 }}
spec:
  ports:
    - name: schema-registry
      port: {{ $v.service.port }}
    {{- if $v.metrics.enabled }}
    - name: {{ include "cp-schema-registry.metricsPortName" . }}
      port: {{ $v.metrics.port }}
    {{- end }}
  selector:
{{ include "cp-schema-registry.selectorLabels" . | indent 4 }}
