apiVersion: v2
name: cp-schema-registry
description: A Helm chart for Confluent Schema Registry on Kubernetes
type: application
version: 0.2.0
appVersion: "7.9.9"
keywords:
  - kafka
  - schema-registry
  - confluent
sources:
  - https://github.com/shepherd44/helm-charts/tree/main/charts/cp-schema-registry
