{{- $v := include "cp-ksql-server.values" . | fromYaml -}}
{{- if $v.external.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-ksql-server.fullname" . }}-external
  labels:
{{ include "cp-ksql-server.mergedLabels" (list . $v.external.labels) | indent 4 }}
  {{- with (include "cp-ksql-server.mergedAnnotations" (list . $v.external.annotations)) }}
  annotations:
{{ . | indent 4 }}
  {{- end }}
spec:
  type: {{ $v.external.type }}
  externalTrafficPolicy: {{ $v.external.externalTrafficPolicy }}
  {{- with $v.external.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml . | indent 4 }}
  {{- end }}
  ports:
    - name: server-proxy
      port: {{ $v.external.port }}
      targetPort: {{ $v.service.port }}
  selector:
{{ include "cp-ksql-server.selectorLabels" . | indent 4 }}
{{- end }}
