{{- $v := include "cp-ksql-server.values" . | fromYaml -}}
{{- if $v.metrics.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cp-ksql-server.fullname" . }}-jmx-configmap
  labels:
{{ include "cp-ksql-server.mergedLabels" (list . dict) | indent 4 }}
  {{- with (include "cp-ksql-server.mergedAnnotations" (list . dict)) }}
  annotations:
{{ . | indent 4 }}
  {{- end }}
data:
  jmx-ksql-server-prometheus.yml: |+
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:{{ $v.jmx.port }}/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
    whitelistObjectNames:
    - io.confluent.ksql.metrics:type=ksql-engine-query-stats
    rules:
    - pattern : 'io.confluent.ksql.metrics<type=ksql-engine-query-stats>([^:]+):'
      name: "cp_ksql_server_metrics_$1"
{{- end }}
