{{- $v := include "cp-ksql-server.values" . | fromYaml -}}
{{- if $v.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cp-ksql-server.serviceAccountName" . }}
  labels:
{{ include "cp-ksql-server.mergedLabels" (list . $v.serviceAccount.labels) | indent 4 }}
  {{- with (include "cp-ksql-server.mergedAnnotations" (list . $v.serviceAccount.annotations)) }}
  annotations:
{{ . | indent 4 }}
  {{- end }}
{{- end }}
